const canvas=document.getElementById('c'),ctx=canvas.getContext('2d');let W=0,H=0,dpr=Math.max(1,devicePixelRatio||1);function resize(){W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const menu=document.getElementById('menu'),up=document.getElementById('upgrade'),choices=document.getElementById('choices'),touch=document.getElementById('touch');
let running=false,last=0,keys={},mouse={x:0,y:0,down:false};addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key==='Shift')dash()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);addEventListener('pointermove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});addEventListener('pointerdown',e=>{mouse.down=true;mouse.x=e.clientX;mouse.y=e.clientY});addEventListener('pointerup',()=>mouse.down=false);
const p={x:0,y:0,r:16,hp:100,max:100,speed:215,fire:0,shots:0,damage:18,bulletSpeed:520,dash:0,coins:0,xp:0,level:1};let bullets=[],enemies=[],particles=[],wave=0,spawnClock=0,waveClock=0,spawnLeft=0,interWave=2,upgradeOpen=false;
function reset(){Object.assign(p,{x:W/2,y:H/2,r:16,hp:100,max:100,speed:215,fire:0,shots:0,damage:18,bulletSpeed:520,dash:0,coins:0,xp:0,level:1});bullets=[];enemies=[];particles=[];wave=0;spawnClock=0;waveClock=0;spawnLeft=0;interWave=1.5;upgradeOpen=false;menu.classList.add('hidden');up.classList.add('hidden');touch.classList.remove('hidden');running=true}
function start(){reset(); requestAnimationFrame(loop)}document.getElementById('start').onclick=start;
function burst(x,y,c,n=8){for(let i=0;i<n;i++)particles.push({x,y,a:Math.random()*6.28,s:50+Math.random()*150,l:.4+rnd(.4),c})}function rnd(v){return Math.random()*v}
function newWave(){wave++;spawnLeft=5+wave*2;spawnClock=.1;waveClock=0;document.getElementById('wave').textContent='WAVE '+wave}
function spawn(){const side=Math.floor(Math.random()*4),m=28;let x=side%2? (side===1?W-m:m):rnd(W),y=side%2?rnd(H):(side===0?m:H-m);let type=wave>5&&Math.random()<.2?'shooter':(Math.random()<.18?'tank':'grunt');let scale=1+Math.min(.65,wave*.045);enemies.push({x,y,type,hp:(type==='tank'?65:32)*scale,max:(type==='tank'?65:32)*scale,r:type==='tank'?21:14,spd:(type==='tank'?52:72)*(1+wave*.01),hit:0,shot:1+Math.random()*1.3})}
function shoot(){const a=Math.atan2(mouse.y-p.y,mouse.x-p.x),b={x:p.x+Math.cos(a)*18,y:p.y+Math.sin(a)*18,vx:Math.cos(a)*p.bulletSpeed,vy:Math.sin(a)*p.bulletSpeed,life:1.2,d:p.damage};bullets.push(b);p.fire=.16;burst(b.x,b.y,'#9be7ff',2)}
function dash(){if(!running||p.dash>0)return;let dx=(keys.d||0)-(keys.a||0),dy=(keys.s||0)-(keys.w||0);if(!dx&&!dy){const a=Math.atan2(mouse.y-p.y,mouse.x-p.x);dx=Math.cos(a);dy=Math.sin(a)}const l=Math.hypot(dx,dy)||1;p.x+=dx/l*125;p.y+=dy/l*125;p.dash=2;burst(p.x,p.y,'#66cfff',14)}
const opts=[['PLASMA CORE','Damage +22%'],['THRUSTER','Move speed +18%'],['REPAIR','Restore 30 HP'],['MAGNET','XP pickup radius +40'],['COIL','Fire rate +18%'],['BULLET','Projectile speed +25%']];let xr=0;
function openUpgrade(){running=false;up.classList.remove('hidden');choices.innerHTML='';opts.sort(()=>Math.random()-.5).slice(0,3).forEach(([a,b])=>{const d=document.createElement('button');d.className='choice';d.innerHTML=`<b>${a}</b><span>${b}</span>`;d.onclick=()=>{apply(a);up.classList.add('hidden');running=true;requestAnimationFrame(loop)};choices.appendChild(d)})}
function apply(a){if(a==='PLASMA CORE')p.damage*=1.22; if(a==='THRUSTER')p.speed*=1.18; if(a==='REPAIR')p.hp=Math.min(p.max,p.hp+30); if(a==='MAGNET')xr+=.4; if(a==='COIL')p.fire=Math.max(.07,p.fire*.82); if(a==='BULLET')p.bulletSpeed*=1.25}
function loop(t){if(!running)return;const dt=Math.min(.033,(t-last)/1000||.016);last=t;update(dt);draw();requestAnimationFrame(loop)}
function update(dt){p.fire=Math.max(0,p.fire-dt);p.dash=Math.max(0,p.dash-dt);if(wave===0){interWave-=dt;if(interWave<=0)newWave()}else if(spawnLeft>0){spawnClock-=dt;if(spawnClock<=0){spawn();spawnLeft--;spawnClock=Math.max(.24,1.1-wave*.025)}}else if(!enemies.length){waveClock+=dt;if(waveClock>1.5){if(p.xp>=p.level*120){p.xp-=p.level*120;p.level++;openUpgrade();return}newWave()}}if((keys.w||keys.a||keys.s||keys.d)){let dx=(keys.d?1:0)-(keys.a?1:0),dy=(keys.s?1:0)-(keys.w?1:0),l=Math.hypot(dx,dy)||1;p.x+=dx/l*p.speed*dt;p.y+=dy/l*p.speed*dt}p.x=Math.max(20,Math.min(W-20,p.x));p.y=Math.max(20,Math.min(H-20,p.y));if(mouse.down&&p.fire<=0)shoot();for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt}bullets=bullets.filter(b=>b.life>0&&b.x>-30&&b.x<W+30&&b.y>-30&&b.y<H+30);for(const e of enemies){const a=Math.atan2(p.y-e.y,p.x-e.x);e.x+=Math.cos(a)*e.spd*dt;e.y+=Math.sin(a)*e.spd*dt;e.shot-=dt;if(e.type==='shooter'&&e.shot<=0){const ba=Math.atan2(p.y-e.y,p.x-e.x);bullets.push({x:e.x,y:e.y,vx:Math.cos(ba)*240,vy:Math.sin(ba)*240,life:2,d:8,enemy:1});e.shot=1.8+Math.random()*1.2}const dist=Math.hypot(p.x-e.x,p.y-e.y);if(dist<e.r+p.r){p.hp-= (e.type==='tank'?12:7)*dt;if(p.hp<=0){running=false;menu.classList.remove('hidden');menu.querySelector('h1').textContent='MISSION FAILED';menu.querySelector('p').textContent='Reach higher waves and upgrade your pilot.'}}}
for(let i=0;i<bullets.length;i++){const b=bullets[i];if(b.enemy){if(Math.hypot(b.x-p.x,b.y-p.y)<p.r+4){p.hp-=b.d;bullets.splice(i,1);i--;continue}}else{for(let j=0;j<enemies.length;j++){const e=enemies[j];if(Math.hypot(b.x-e.x,b.y-e.y)<e.r+4){e.hp-=b.d;bullets.splice(i,1);i--;burst(e.x,e.y,'#7ee8ff',4);if(e.hp<=0){p.xp+=e.type==='tank'?45:24;p.coins+=e.type==='tank'?8:3;burst(e.x,e.y,e.type==='tank'?'#ff7b8a':'#d4f4ff',12);enemies.splice(j,1)}break}}}}
for(const q of particles){q.x+=Math.cos(q.a)*q.s*dt;q.y+=Math.sin(q.a)*q.s*dt;q.s*=.94;q.l-=dt}particles=particles.filter(q=>q.l>0);document.getElementById('hp').textContent='HP '+Math.max(0,Math.floor(p.hp));document.getElementById('xp').textContent='XP '+Math.floor(p.xp)+' / '+(p.level*120);document.getElementById('coins').textContent='◈ '+p.coins}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#06101b';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(85,170,255,.08)';for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const q of particles){ctx.globalAlpha=Math.max(0,q.l*2);ctx.fillStyle=q.c;ctx.beginPath();ctx.arc(q.x,q.y,3+q.l*2,0,6.28);ctx.fill()}ctx.globalAlpha=1;for(const b of bullets){ctx.strokeStyle=b.enemy?'#ff7b8a':'#9be7ff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x-b.vx*.02,b.y-b.vy*.02);ctx.lineTo(b.x,b.y);ctx.stroke()}for(const e of enemies){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.type==='tank'?'#ff6076':e.type==='shooter'?'#c07cff':'#79d8ff';ctx.shadowBlur=18;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.arc(0,0,e.r,0,6.28);ctx.fill();ctx.fillStyle='#06101b';ctx.beginPath();ctx.arc(0,0,4,0,6.28);ctx.fill();ctx.restore()}ctx.save();ctx.translate(p.x,p.y);const ang=Math.atan2(mouse.y-p.y,mouse.x-p.x);ctx.rotate(ang);ctx.fillStyle='#dff9ff';ctx.shadowBlur=24;ctx.shadowColor='#4ec7ff';ctx.beginPath();ctx.moveTo(21,0);ctx.lineTo(-13,-11);ctx.lineTo(-7,0);ctx.lineTo(-13,11);ctx.closePath();ctx.fill();ctx.fillStyle='#6bcfff';ctx.fillRect(5,-3,13,6);ctx.restore()}
