const c=document.getElementById('game'),x=c.getContext('2d');const W=960,H=540;function fit(){const r=c.getBoundingClientRect();return{x:(innerWidth/W),y:(innerHeight/H)}}function clamp(v,a,b){return Math.max(a,Math.min(b,v))}function rand(a,b){return a+Math.random()*(b-a)}function rgb(a){return a}
const menu=document.getElementById('menu'),upgrade=document.getElementById('upgrade'),pause=document.getElementById('pause'),over=document.getElementById('over'),cards=document.getElementById('cards');let state='menu',demo=false,last=performance.now(),time=0,wave=1,score=0,credits=0,level=1,xp=0,nextXp=100,spawn=0,enemies=[],shots=[],particles=[],bosses=[],powerups=[],keys={},fireHeld=false,shootCd=0,shake=0,combo=0;let ship={x:140,y:270,hp:100,maxHp:100,speed:280,damage:1,rate:.22,shotSpeed:620,dash:0,dashCd:0};
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=1;if(e.key==='Escape'){if(state==='play'){state='pause';pause.classList.remove('hidden')}else if(state==='pause'){state='play';pause.classList.add('hidden')}}if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=0);c.addEventListener('pointerdown',()=>{fireHeld=true});c.addEventListener('pointerup',()=>{fireHeld=false});c.addEventListener('pointerleave',()=>{fireHeld=false});function pointer(e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}c.addEventListener('pointermove',e=>{if(state==='play'){const p=pointer(e);ship.targetY=p.y}});
function hideAll(){[menu,upgrade,pause,over].forEach(e=>e.classList.add('hidden'))}function reset(){wave=1;score=0;credits=0;level=1;xp=0;nextXp=100;enemies=[];shots=[];particles=[];powerups=[];ship={x:140,y:270,hp:100,maxHp:100,speed:280,damage:1,rate:.22,shotSpeed:620,dash:0,dashCd:0,targetY:270};state='menu';demo=false;hideAll();menu.classList.remove('hidden')}function start(){resetRun();state='play';hideAll()}function resetRun(){wave=1;score=0;credits=0;level=1;xp=0;nextXp=100;enemies=[];shots=[];particles=[];powerups=[];ship={x:140,y:270,hp:100,maxHp:100,speed:280,damage:1,rate:.22,shotSpeed:620,dash:0,dashCd:0,targetY:270};demo=false;spawn=0;combo=0}function demoMode(){resetRun();state='demo';hideAll();menu.classList.remove('hidden');document.getElementById('demo').textContent='Demo Running'}
function addFx(px,py,col,n=10){for(let i=0;i<n;i++)particles.push({x:px,y:py,vx:rand(-150,150),vy:rand(-150,150),life:rand(.25,.7),col})}
function spawnEnemy(){const types=['scout','bomber','hunter'];const t=types[Math.floor(Math.random()*types.length)];const y=rand(60,480);const base={x:1000,y,hp:t==='bomber'?7:t==='hunter'?4:2.5,maxHp:t==='bomber'?7:t==='hunter'?4:2.5,type:t,spd:t==='bomber'?62:t==='hunter'?118:172,shoot:t==='hunter'?1.15:999,phase:rand(0,6)};enemies.push(base)}
function spawnBoss(){enemies.push({boss:true,x:1080,y:270,hp:90+wave*14,maxHp:90+wave*14,type:'boss',spd:48,shoot:1.05,phase:0})}
function fire(){if(shootCd>0)return;shootCd=ship.rate;shots.push({x:ship.x+28,y:ship.y,vx:ship.shotSpeed,vy:0,damage:ship.damage,life:1.6});addFx(ship.x+25,ship.y,'#8deaff',4)}
function levelUp(){xp-=nextXp;nextXp=Math.round(nextXp*1.2);level++;state='upgrade';upgrade.classList.remove('hidden');cards.innerHTML='';const opts=[['Overclock','Fire rate +18%',()=>ship.rate=Math.max(.09,ship.rate*.82)],['Plasma Core','Damage +1',()=>ship.damage++],['Shield Matrix','Max hull +20',()=>{ship.maxHp+=20;ship.hp+=20}]];opts.forEach(([a,b,fn])=>{const d=document.createElement('button');d.className='card';d.innerHTML=`<b>${a}</b><span>${b}</span>`;d.onclick=()=>{fn();upgrade.classList.add('hidden');state='play'};cards.appendChild(d)})}
function end(){state='over';document.getElementById('summary').innerHTML=`Wave <b>${wave}</b> · Level <b>${level}</b> · Score <b>${score.toLocaleString()}</b> · Credits <b>${credits}</b>`;over.classList.remove('hidden')}
function update(dt){time+=dt;shootCd=Math.max(0,shootCd-dt);ship.dashCd=Math.max(0,ship.dashCd-dt);shake=Math.max(0,shake-dt);if(state==='menu'||state==='demo'){ship.y=270+Math.sin(time*.9)*110;for(const e of enemies)e.x-=e.spd*dt*.45;if(Math.random()<dt*.6)spawnEnemy();if(enemies.length<5)spawnEnemy();return}if(state!=='play')return;
let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);if(keys.shift&&ship.dashCd<=0){ship.dashCd=1.5;ship.x=clamp(ship.x+dx*130,55,370);addFx(ship.x,ship.y,'#fff',18)}ship.x=clamp(ship.x+dx*ship.speed*dt,55,390);ship.y=clamp(ship.y+dy*ship.speed*dt,55,485);if(keys.space||fireHeld)fire();spawn-=dt;if(spawn<=0){spawn=Math.max(.35,.95-wave*.025);if(wave%4===0&&enemies.filter(e=>e.boss).length===0&&Math.random()<.35)spawnBoss();else spawnEnemy()}
for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt}shots=shots.filter(s=>s.life>0&&s.x<1030);for(const e of enemies){e.x-=e.spd*dt;e.phase+=dt;if(e.type==='hunter'&&!e.boss&&e.x<850){e.y+=Math.sin(e.phase*2)*18*dt}if(e.boss){e.y=270+Math.sin(e.phase*.8)*120}e.shoot-=dt;if(e.shoot<=0&&e.x<950){e.shoot=e.boss?.95:1.9;shots.push({x:e.x-20,y:e.y,vx:-280,vy:(ship.y-e.y)*.22,damage:e.boss?7:4,enemy:1,life:3})}}
for(let i=enemies.length-1;i>=0;i--){
 const e=enemies[i];
 for(let j=shots.length-1;j>=0;j--){
  const sh=shots[j];
  if(!sh.enemy && Math.hypot(sh.x-e.x,sh.y-e.y)<(e.boss?48:24)){
   e.hp-=sh.damage; shots.splice(j,1); addFx(sh.x,sh.y,'#ffb07c',5);
   if(e.hp<=0){
    const val=e.boss?250:e.type==='bomber'?60:35;
    score+=val; credits+=e.boss?60:12; xp+=e.boss?90:22; combo++;
    addFx(e.x,e.y,e.boss?'#b16bff':'#ff6e9b',e.boss?40:12);
    enemies.splice(i,1);
    if(xp>=nextXp) levelUp();
    break;
   }
  }
 }
}
for(let i=shots.length-1;i>=0;i--){const s=shots[i];if(s.enemy&&Math.hypot(s.x-ship.x,s.y-ship.y)<22){shots.splice(i,1);ship.hp-=s.damage;shake=.15;addFx(ship.x,ship.y,'#ff5f7c',12)}}for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(Math.hypot(e.x-ship.x,e.y-ship.y)<(e.boss?52:25)){ship.hp-=e.boss?11:5;addFx(e.x,e.y,'#ff5f7c',16);enemies.splice(i,1);shake=.18}}if(ship.hp<=0)return end();if(enemies.length===0&&wave%1===0&&score>0&&Math.random()<dt*.3){wave++;ship.hp=clamp(ship.hp+8,0,ship.maxHp)}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt}particles=particles.filter(p=>p.life>0)}
function draw(){const g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#050815');g.addColorStop(1,'#0b1230');x.fillStyle=g;x.fillRect(0,0,W,H);const off=state==='play'&&shake?rand(-3,3):0;x.save();x.translate(off,off);for(let i=0;i<90;i++){const sx=(i*117-(time*(20+(i%5)*7)))%W;const sy=(i*71)%H;x.fillStyle=i%9===0?'#85c9ff':'rgba(180,210,255,.5)';x.fillRect((sx+W)%W,sy, i%7===0?2:1, i%7===0?2:1)}for(const e of enemies){const imgType=e.boss?'#9a62ff':e.type==='bomber'?'#ff9b5e':e.type==='hunter'?'#ff5f90':'#62d8ff';x.save();x.translate(e.x,e.y);x.rotate(Math.sin(e.phase)*.08);x.fillStyle=imgType;x.shadowBlur=e.boss?24:12;x.shadowColor=imgType;x.beginPath();x.moveTo(-26,0);x.lineTo(10,-18);x.lineTo(28,0);x.lineTo(10,18);x.closePath();x.fill();x.fillStyle='#09111e';x.beginPath();x.arc(4,0,e.boss?15:7,0,Math.PI*2);x.fill();x.restore();x.fillStyle='rgba(255,255,255,.1)';x.fillRect(e.x-(e.boss?40:18),e.y-(e.boss?52:34),(e.boss?80:36),3);x.fillStyle='#69e8ff';x.fillRect(e.x-(e.boss?40:18),e.y-(e.boss?52:34),(e.boss?80:36)*Math.max(0,e.hp/e.maxHp),3)}for(const s of shots){x.fillStyle=s.enemy?'#ff547b':'#8df0ff';x.shadowBlur=14;x.shadowColor=x.fillStyle;x.fillRect(s.x-6,s.y-2,12,4);x.shadowBlur=0}for(const p of particles){x.globalAlpha=Math.max(0,p.life*2);x.fillStyle=p.col;x.fillRect(p.x,p.y,3,3);x.globalAlpha=1}x.save();x.translate(ship.x,ship.y);x.rotate(Math.sin(time*5)*.02);x.fillStyle='#70e9ff';x.shadowBlur=24;x.shadowColor='#63e6ff';x.beginPath();x.moveTo(34,0);x.lineTo(-22,-17);x.lineTo(-8,0);x.lineTo(-22,17);x.closePath();x.fill();x.fillStyle='#0b1220';x.beginPath();x.arc(2,0,7,0,Math.PI*2);x.fill();x.restore();x.restore()}
function frame(t){const dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();document.getElementById('wave').textContent=wave;document.getElementById('score').textContent=score.toLocaleString();document.getElementById('credits').textContent=credits;document.getElementById('level').textContent=level;document.getElementById('hp').style.transform=`scaleX(${ship.hp/ship.maxHp})`;document.getElementById('xp').style.transform=`scaleX(${xp/nextXp})`;requestAnimationFrame(frame)}
document.getElementById('start').onclick=start;document.getElementById('demo').onclick=()=>{demo=true;resetRun();state='demo';document.getElementById('demo').textContent='Demo Running'};document.getElementById('resume').onclick=()=>{state='play';pause.classList.add('hidden')};document.getElementById('menuBtn').onclick=()=>{state='menu';pause.classList.add('hidden');menu.classList.remove('hidden')};document.getElementById('again').onclick=start;document.getElementById('back').onclick=reset;reset();requestAnimationFrame(frame);
